services:

  frontend:
    image: frontend
    build: ./Frontend/
    container_name: frontend
    ports:
    - 1234:80

  api:
    image: api
    build: ./Api/DockerCourseWebApi/
    container_name: api 
    ports:
    - 17860:8080

  database:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Dometrain#123
    ports:
      - 1433:1433

  database-seed:
    depends_on: [database]
    build:  
      context: Database/
      dockerfile:  Dockerfile
    container_name: database-seed

  